In [1]:
import torch

In [2]:
num_entries = 5000

In [3]:
db = torch.rand(num_entries) > 0.5

In [4]:
db

tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8)

In [7]:
db[0:5]

tensor([0, 1, 1, 0, 1], dtype=torch.uint8)

In [8]:
remove_index = 2

In [9]:
db[0:2]

tensor([0, 1], dtype=torch.uint8)

In [10]:
db[3:]

tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8)

In [20]:
def get_parallel_db(db, remove_index):
    return torch.cat((db[0:remove_index], db[remove_index+1:]))

In [21]:
get_parallel_db(db, 2)[0:5]

tensor([0, 1, 0, 1, 1], dtype=torch.uint8)

In [22]:
get_parallel_db(db, 0).shape

torch.Size([4999])

In [23]:
get_parallel_db(db, 52352)

tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8)

In [24]:
def get_parallel_dbs(db):
    
    parallel_dbs = list()
    
    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
        
    return parallel_dbs

In [25]:
pdbs = get_parallel_dbs(db)

In [26]:
pdbs

[tensor([1, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 1, 1,  ..., 0, 1

In [30]:
def create_db_and_parallels(num_entries):
    
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

In [31]:
db, pdbs = create_db_and_parallels(20)

In [33]:
pdbs

[tensor([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1],
        dtype=torch.uint8),
 tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,